# Generated by Django 5.2.17 on 2026-09-10 05:58

import django.db.models.deletion
import stacos.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('fact_type', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=16)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('nullable', models.BooleanField(default=True)),
                ('effective_dated', models.BooleanField(default=False)),
                ('depends_on', models.JSONField(blank=True, default=list)),
                ('help_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='JurisdictionPack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(help_text='ISO-3166-1 alpha-2.', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(help_text='ISO-4217.', max_length=3)),
                ('currency_symbol', models.CharField(default='', max_length=8)),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('default_locale', models.CharField(default='en', max_length=12)),
                ('digit_grouping', models.CharField(choices=[('INDIAN', 'Indian (1,23,45,678)'), ('WESTERN', 'Western (12,345,678)')], default='WESTERN', max_length=10)),
                ('fy_start_month', models.PositiveSmallIntegerField(default=1)),
                ('fy_start_day', models.PositiveSmallIntegerField(default=1)),
                ('fy_label_template', models.CharField(default='FY {start_year}', help_text="e.g. 'FY {start_year}-{end_year_short}' renders as FY 2026-27.", max_length=60)),
                ('sub_jurisdictions', models.JSONField(blank=True, default=list)),
                ('entity_types', models.JSONField(blank=True, default=list)),
                ('registration_types', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('contributed_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='e.g. IN-NATIONAL, IN-GJ.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sub_jurisdiction', models.CharField(blank=True, max_length=12)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='jurisdictions.jurisdictionpack')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. CBIC, CBDT, MCA, EPFO.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('sub_jurisdiction', models.CharField(blank=True, max_length=12)),
                ('website', models.URLField(blank=True)),
                ('portal_url', models.URLField(blank=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='jurisdictions.jurisdictionpack')),
            ],
            options={
                'verbose_name_plural': 'authorities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('is_restricted', models.BooleanField(default=False, help_text='Optional holiday — offices may or may not close.')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='jurisdictions.holidaycalendar')),
            ],
            options={
                'ordering': ['calendar', 'date'],
                'indexes': [models.Index(fields=['calendar', 'date'], name='holiday_cal_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('calendar', 'date'), name='holiday_calendar_date_uniq')],
            },
        ),
        migrations.CreateModel(
            name='WeekendRule',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('weekend_days', models.JSONField(default=list)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekend_rules', to='jurisdictions.jurisdictionpack')),
            ],
            options={
                'ordering': ['pack', 'valid_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='weekendrule_window_sane')],
            },
        ),
    ]
