# Generated by Django 5.2.17 on 2026-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jurisdictions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurisdictionpack",
            name="registration_types",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
