# Generated by Django 5.2.17 on 2026-08-12 06:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurisdictions', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('reference_number', models.CharField(help_text="The authority's own reference — DIN, notice number, order number.", max_length=120)),
                ('notice_type', models.CharField(choices=[('SCRUTINY', 'Scrutiny or assessment'), ('DEMAND', 'Demand'), ('SHOW_CAUSE', 'Show cause'), ('DEFECTIVE_RETURN', 'Defective return'), ('MISMATCH', 'Mismatch or intimation'), ('PENALTY', 'Penalty'), ('REFUND', 'Refund'), ('SUMMONS', 'Summons'), ('INSPECTION', 'Inspection or survey'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('statutory_reference', models.CharField(blank=True, help_text="e.g. 'Section 143(2) Income-tax Act'.", max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('period_key', models.CharField(blank=True, db_index=True, max_length=32)),
                ('financial_years', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('received_on', models.DateField(db_index=True)),
                ('respond_by', models.DateField(blank=True, db_index=True, null=True)),
                ('demand_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('accepted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('state', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUESTED', 'Information requested from client'), ('DRAFTING', 'Drafting a response'), ('PENDING_APPROVAL', 'Pending client approval'), ('RESPONDED', 'Responded'), ('FOLLOW_UP', 'Further correspondence received'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated to appeal')], db_index=True, default='RECEIVED', max_length=20)),
                ('risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered by a user'), ('EMAIL', 'Ingested from email'), ('PORTAL', 'Retrieved from a portal')], default='MANUAL', max_length=8)),
                ('responded_on', models.DateField(blank=True, null=True)),
                ('response_reference', models.CharField(blank=True, max_length=120)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_notices', to=settings.AUTH_USER_MODEL)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='jurisdictions.authority')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['respond_by', '-received_on'],
            },
        ),
        migrations.CreateModel(
            name='NoticeEvent',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('RECEIVED', 'Notice received'), ('STATE_CHANGED', 'State changed'), ('INFO_REQUESTED', 'Information requested'), ('RESPONSE_DRAFTED', 'Response drafted'), ('RESPONSE_FILED', 'Response filed'), ('FOLLOW_UP', 'Further correspondence'), ('HEARING', 'Hearing attended'), ('ORDER', 'Order received'), ('NOTE', 'Note')], max_length=20)),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(blank=True, max_length=20)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, help_text='The date it happened, which is often not the date it was recorded.')),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_events', to='tenancy.entity')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notices.notice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(condition=models.Q(('state__in', ['DRAFTING', 'FOLLOW_UP', 'INFO_REQUESTED', 'PENDING_APPROVAL', 'RECEIVED', 'UNDER_REVIEW']), ('archived_at__isnull', True)), fields=['tenant', 'respond_by'], name='notice_open_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['entity', '-received_on'], name='notice_entity_recv_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['assigned_to', 'respond_by'], name='notice_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('entity', 'authority', 'reference_number'), name='notice_reference_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.CheckConstraint(condition=models.Q(('issued_on__isnull', True), ('received_on__gte', models.F('issued_on')), _connector='OR'), name='notice_received_after_issued'),
        ),
        migrations.AddIndex(
            model_name='noticeevent',
            index=models.Index(fields=['notice', '-occurred_at'], name='noticeevent_timeline_idx'),
        ),
    ]
