# Generated by Django 5.2.17 on 2026-08-11 19:31

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ENDED', 'Ended'), ('DECLINED', 'Declined')], default='INVITED', max_length=12)),
                ('initiated_by_side', models.CharField(choices=[('ORGANISATION', 'The business invited the firm'), ('PRACTICE', 'The firm invited the business')], max_length=16)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance')], max_length=32), blank=True, default=list, size=None)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('engagement_letter_ref', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=250)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_approved', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_ended', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='tenancy.entity')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_invited', to=settings.AUTH_USER_MODEL)),
                ('practice_tenant', models.ForeignKey(limit_choices_to={'type': 'PRACTICE'}, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='tenancy.tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_phone_e164', models.CharField(blank=True, max_length=20)),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('initiated_by_side', models.CharField(choices=[('ORGANISATION', 'The business invited the firm'), ('PRACTICE', 'The firm invited the business')], max_length=16)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance')], max_length=32), blank=True, default=list, size=None)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='SENT', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_invitations', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='engagements.engagement')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenancy.entity')),
                ('from_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='tenancy.tenant')),
                ('to_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['practice_tenant', 'status'], name='engagement_practice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['tenant', 'status'], name='engagement_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['entity', 'status'], name='engagement_entity_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['INVITED', 'ACTIVE', 'SUSPENDED'])), fields=('practice_tenant', 'entity'), name='engagement_live_unique'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='engagement_window_sane'),
        ),
        migrations.AddIndex(
            model_name='engagementinvitation',
            index=models.Index(fields=['to_email', 'status'], name='invite_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementinvitation',
            index=models.Index(fields=['from_tenant', 'status'], name='invite_from_status_idx'),
        ),
    ]
