# Generated by Django 5.2.17 on 2026-09-29 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance'), ('OTHER', 'Other')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='engagementinvitation',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance'), ('OTHER', 'Other')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
