# Generated by Django 5.2.17 on 2026-08-11 18:38

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurisdictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=250)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('STRUCK_OFF', 'Struck off'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=12)),
                ('entity_type', models.CharField(max_length=24)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('cessation_date', models.DateField(blank=True, null=True)),
                ('registered_office_state', models.CharField(blank=True, max_length=12)),
                ('registered_office_address', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='tenancy.entity')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ORGANISATION', 'Business'), ('PRACTICE', 'Professional firm'), ('DEALER', 'Channel partner')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Payment overdue'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='TRIAL', max_length=12)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('logo_url', models.URLField(blank=True)),
                ('jurisdiction_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='jurisdictions.jurisdictionpack')),
                ('managed_by_dealer', models.ForeignKey(blank=True, limit_choices_to={'type': 'DEALER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tenants', to='tenancy.tenant')),
                ('parent_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_dealers', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('tenant_type', models.CharField(choices=[('ORGANISATION', 'Business'), ('PRACTICE', 'Professional firm'), ('DEALER', 'Channel partner')], max_length=16)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('rank', models.PositiveSmallIntegerField(default=100, help_text='Lower is more senior. Used for ordering, not for authority.')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['tenant_type', 'rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], default='INVITED', max_length=12)),
                ('all_entities', models.BooleanField(default=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance')], max_length=32), blank=True, default=list, size=None)),
                ('department', models.CharField(blank=True, max_length=60)),
                ('extra_permissions', models.JSONField(blank=True, default=list)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('entities', models.ManyToManyField(blank=True, related_name='memberships', to='tenancy.entity')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.role')),
                ('client_tenants', models.ManyToManyField(blank=True, related_name='practice_members', to='tenancy.tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EntityRegistration',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('type', models.CharField(db_index=True, max_length=24)),
                ('value', models.CharField(max_length=64)),
                ('jurisdiction', models.CharField(blank=True, help_text='Sub-jurisdiction code, e.g. IN-GJ for a state GSTIN.', max_length=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tenancy.entity')),
                ('issuing_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurisdictions.authority')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['entity', 'type', 'jurisdiction'],
            },
        ),
        migrations.CreateModel(
            name='EntityProfile',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('contractor_count', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_up_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('nic_code', models.CharField(blank=True, max_length=12)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('sub_sector', models.CharField(blank=True, max_length=100)),
                ('states_of_operation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default=list, size=None)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EntityPremises',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=24)),
                ('jurisdiction', models.CharField(blank=True, max_length=12)),
                ('address', models.TextField(blank=True)),
                ('operational_from', models.DateField(blank=True, null=True)),
                ('operational_to', models.DateField(blank=True, null=True)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'entity premises',
                'ordering': ['entity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EntityFactValue',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('value', models.JSONField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('USER', 'Entered by a user'), ('IMPORT', 'Imported from books'), ('PORTAL', 'Fetched from a government portal'), ('DERIVED', 'Computed')], default='USER', max_length=12)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_values', to='tenancy.entity')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['entity', 'key', '-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['type', 'status'], name='tenant_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['managed_by_dealer'], name='tenant_dealer_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('code', 'tenant_type'), name='role_system_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'code'), name='role_tenant_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='membership_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant', 'status'], name='membership_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='membership_tenant_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='entityregistration',
            index=models.Index(fields=['tenant', 'type'], name='entityreg_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='entityregistration',
            index=models.Index(fields=['type', 'value'], name='entityreg_type_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('valid_to__isnull', True)), fields=('entity', 'type', 'jurisdiction'), name='entityreg_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='entityregistration',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='entityreg_window_sane'),
        ),
        migrations.AddIndex(
            model_name='entityprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['facts'], name='entityprofile_facts_gin'),
        ),
        migrations.AddIndex(
            model_name='entityprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['states_of_operation'], name='entityprofile_states_gin'),
        ),
        migrations.AddIndex(
            model_name='entityprofile',
            index=models.Index(fields=['tenant', 'entity'], name='entityprofile_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='entitypremises',
            index=models.Index(fields=['tenant', 'type'], name='premises_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='entitypremises',
            index=django.contrib.postgres.indexes.GinIndex(fields=['facts'], name='premises_facts_gin'),
        ),
        migrations.AddIndex(
            model_name='entityfactvalue',
            index=models.Index(fields=['entity', 'key', '-valid_from'], name='factvalue_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='entityfactvalue',
            index=models.Index(fields=['tenant', 'key'], name='factvalue_tenant_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityfactvalue',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='factvalue_window_sane'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'status'], name='entity_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'name'], name='entity_tenant_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), models.Q(('short_code', ''), _negated=True)), fields=('tenant', 'short_code'), name='entity_tenant_shortcode_uniq'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.CheckConstraint(condition=models.Q(('cessation_date__isnull', True), ('incorporation_date__isnull', True), ('cessation_date__gte', models.F('incorporation_date')), _connector='OR'), name='entity_cessation_after_incorporation'),
        ),
    ]
