# Generated by Django 5.2.17 on 2026-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='setup_step',
            field=models.CharField(choices=[('registrations', 'Registrations'), ('answers', 'Answer what applies'), ('packs', 'Optional add-ons'), ('build', 'Review and create')], default='registrations', help_text='Furthest step reached in the guided first-run setup.', max_length=16),
        ),
    ]
