# Generated by Django 5.2.17 on 2026-09-28 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_entity_setup_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinvitation',
            name='all_entities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='client_tenants',
            field=models.ManyToManyField(blank=True, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='+', to='tenancy.entity'),
        ),
    ]
