# Generated by Django 5.2.17 on 2026-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_invitation_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='revoked_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
