# Generated by Django 5.2.17 on 2026-09-29 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_member_revoked_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='setup_step',
            field=models.CharField(choices=[('registrations', 'Registrations'), ('answers', 'Answer what applies'), ('build', 'Review and create')], default='registrations', help_text='Furthest step reached in the guided first-run setup.', max_length=16),
        ),
        migrations.AlterField(
            model_name='membership',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance'), ('OTHER', 'Other')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAX_INDIRECT', 'Indirect tax'), ('TAX_DIRECT', 'Direct tax'), ('CORPORATE_SECRETARIAL', 'Corporate secretarial'), ('LABOUR', 'Labour and employment'), ('ENVIRONMENT', 'Environment'), ('SAFETY_FIRE', 'Safety and fire'), ('LICENSING', 'Licensing'), ('FEMA_RBI', 'Foreign exchange and RBI'), ('SECTORAL', 'Sector-specific'), ('DATA_PRIVACY', 'Data privacy'), ('INTERNAL_GOVERNANCE', 'Internal governance'), ('OTHER', 'Other')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
