# Generated by Django 5.2.17 on 2026-09-10 05:58

import django.db.models.deletion
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('OBLIGATION_DUE', 'A filing is coming up'), ('OBLIGATION_OVERDUE', 'A filing is overdue'), ('OBLIGATION_DATE_CHANGED', 'A due date moved'), ('REQUEST_SENT', 'Information has been requested from you'), ('REQUEST_REMINDER', 'A reminder about information requested'), ('REQUEST_ANSWERED', 'A client has answered a request'), ('NOTICE_RECEIVED', 'A notice has been recorded'), ('NOTICE_DEADLINE', 'A notice deadline is approaching'), ('RETURN_REVIEW', 'A return is waiting for review'), ('WORK_ASSIGNED', 'Work has been assigned to you'), ('INVOICE_ISSUED', 'An invoice has been issued'), ('INVOICE_OVERDUE', 'An invoice is overdue'), ('DOCUMENT_QUARANTINED', 'A file failed its virus scan'), ('DIGEST', 'Your summary')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('INFO', 'For information'), ('ATTENTION', 'Needs attention'), ('URGENT', 'Urgent')], db_index=True, default='INFO', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=400)),
                ('subject_type', models.CharField(choices=[('OBLIGATION', 'Obligation'), ('REQUEST', 'Information request'), ('NOTICE', 'Notice'), ('RETURN', 'Return'), ('WORK_ITEM', 'Work item'), ('INVOICE', 'Invoice'), ('DOCUMENT', 'Document'), ('NONE', 'Nothing in particular')], default='NONE', max_length=16)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('digested_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenancy.entity')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('IN_APP', 'In the app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('state', models.CharField(choices=[('PENDING', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Delivery failed'), ('SUPPRESSED', 'Not sent — the recipient opted out'), ('NOT_REACHABLE', 'Not sent — the recipient cannot be reached here')], default='PENDING', max_length=14)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('digest', models.CharField(choices=[('IMMEDIATE', 'As things happen'), ('DAILY', 'Once a day'), ('WEEKLY', 'Once a week'), ('OFF', 'In the app only')], default='IMMEDIATE', max_length=10)),
                ('digest_hour', models.PositiveSmallIntegerField(default=7)),
                ('muted_kinds', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('read_at__isnull', True)), fields=['recipient', '-created_at'], name='notification_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', '-created_at'], name='notification_tenant_time_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['subject_type', 'subject_id'], name='notification_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('tenant', 'recipient', 'dedupe_key'), name='notification_dedupe_uniq'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['state', 'created_at'], name='delivery_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='delivery_channel_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='notification_prefs_uniq'),
        ),
    ]
