# Generated by Django 5.2.17 on 2026-08-12 06:56

import django.core.validators
import django.db.models.deletion
import stacos.core.ids
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('BOARD', 'Board meeting'), ('AGM', 'Annual general meeting'), ('EGM', 'Extraordinary general meeting'), ('AUDIT_COMMITTEE', 'Audit committee'), ('CSR_COMMITTEE', 'CSR committee'), ('NRC', 'Nomination and remuneration committee'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('state', models.CharField(choices=[('PLANNED', 'Planned'), ('NOTICE_ISSUED', 'Notice issued'), ('HELD', 'Held'), ('MINUTED', 'Minuted'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=16)),
                ('serial_number', models.CharField(blank=True, help_text="The company's own numbering, e.g. '4th Board Meeting of FY 2026-27'.", max_length=40)),
                ('scheduled_for', models.DateField(db_index=True)),
                ('held_on', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=250)),
                ('is_video_conference', models.BooleanField(default=False)),
                ('notice_issued_on', models.DateField(blank=True, null=True)),
                ('quorum_required', models.PositiveSmallIntegerField(default=2)),
                ('quorum_present', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chairperson', models.CharField(blank=True, max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('minutes_signed_on', models.DateField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='tenancy.entity')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('din', models.CharField(blank=True, help_text='Director Identification Number.', max_length=20)),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director'), ('SHAREHOLDER', 'Shareholder'), ('AUDITOR', 'Auditor'), ('COMPANY_SECRETARY', 'Company secretary'), ('INVITEE', 'Invitee')], default='DIRECTOR', max_length=20)),
                ('attendance', models.CharField(choices=[('PRESENT', 'Present'), ('VIDEO', 'Present by video'), ('PROXY', 'By proxy'), ('LEAVE', 'Leave of absence'), ('ABSENT', 'Absent')], default='PRESENT', max_length=8)),
                ('is_interested', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendees', to='tenancy.entity')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='secretarial.meeting')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['meeting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ORDINARY', 'Ordinary resolution'), ('SPECIAL', 'Special resolution'), ('BOARD', 'Board resolution'), ('CIRCULAR', 'Resolution by circulation'), ('UNANIMOUS', 'Unanimous board resolution')], max_length=12)),
                ('item_number', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('text', models.TextField(blank=True)),
                ('passed_on', models.DateField(db_index=True)),
                ('votes_for', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('votes_against', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abstentions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_mgt14', models.BooleanField(default=False, help_text='Special resolutions and certain board resolutions.')),
                ('mgt14_filed_on', models.DateField(blank=True, null=True)),
                ('mgt14_srn', models.CharField(blank=True, max_length=40)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='tenancy.entity')),
                ('meeting', models.ForeignKey(blank=True, help_text='Null for a resolution passed by circulation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='secretarial.meeting')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-passed_on', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BODY_CORPORATE', 'Body corporate'), ('TRUST', 'Trust'), ('FOREIGN', 'Foreign investor')], default='INDIVIDUAL', max_length=16)),
                ('folio_number', models.CharField(blank=True, max_length=40)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('is_non_resident', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['entity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ALLOTMENT', 'Allotment'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('BUYBACK', 'Buy-back'), ('BONUS', 'Bonus issue'), ('SPLIT', 'Split or consolidation')], max_length=16)),
                ('share_class', models.CharField(choices=[('EQUITY', 'Equity'), ('PREFERENCE', 'Preference'), ('CCPS', 'Compulsorily convertible preference'), ('CCD', 'Compulsorily convertible debenture')], default='EQUITY', max_length=12)),
                ('quantity', models.BigIntegerField()),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('consideration', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('executed_on', models.DateField(db_index=True)),
                ('certificate_number', models.CharField(blank=True, max_length=40)),
                ('distinctive_from', models.BigIntegerField(blank=True, null=True)),
                ('distinctive_to', models.BigIntegerField(blank=True, null=True)),
                ('requires_fcgpr', models.BooleanField(default=False)),
                ('fcgpr_filed_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='tenancy.entity')),
                ('resolution', models.ForeignKey(blank=True, help_text='The board or shareholder resolution that authorised it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_transactions', to='secretarial.resolution')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='secretarial.shareholder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['entity', 'executed_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRegister',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('MEMBERS', 'Register of members'), ('DIRECTORS', 'Register of directors and KMP'), ('CHARGES', 'Register of charges'), ('CONTRACTS', 'Register of contracts with related parties'), ('LOANS', 'Register of loans, guarantees and investments'), ('SBO', 'Register of significant beneficial owners'), ('SHARE_CERTIFICATES', 'Register of share certificates'), ('DEPOSITS', 'Register of deposits')], max_length=24)),
                ('is_maintained', models.BooleanField(default=False)),
                ('kept_at', models.CharField(blank=True, max_length=250)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_registers', to='tenancy.entity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['entity', 'kind'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['entity', 'kind', '-scheduled_for'], name='meeting_entity_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant', 'state'], name='meeting_tenant_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['HELD', 'MINUTED']), _negated=True), ('held_on__isnull', False), _connector='OR'), name='meeting_held_has_date'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.UniqueConstraint(fields=('meeting', 'name'), name='attendee_meeting_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['entity', '-passed_on'], name='resolution_entity_date_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(condition=models.Q(('requires_mgt14', True), ('mgt14_filed_on__isnull', True)), fields=['entity', 'requires_mgt14'], name='resolution_mgt14_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='shareholder',
            constraint=models.UniqueConstraint(condition=models.Q(('folio_number', ''), _negated=True), fields=('entity', 'folio_number'), name='shareholder_folio_uniq'),
        ),
        migrations.AddIndex(
            model_name='sharetransaction',
            index=models.Index(fields=['entity', 'executed_on'], name='sharetxn_entity_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sharetransaction',
            index=models.Index(fields=['shareholder', 'executed_on'], name='sharetxn_holder_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='sharetxn_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='statutoryregister',
            constraint=models.UniqueConstraint(fields=('entity', 'kind'), name='register_entity_kind_uniq'),
        ),
    ]
