# Generated by Django 5.2.17 on 2026-08-12 07:09

import django.core.validators
import django.db.models.deletion
import stacos.core.ids
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('BACKLOG', 'Backlog'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('IN_REVIEW', 'In review'), ('DONE', 'Done')], db_index=True, default='BACKLOG', max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=8)),
                ('obligation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('obligation_title', models.CharField(blank=True, max_length=200)),
                ('due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fixed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=250)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to=settings.AUTH_USER_MODEL)),
                ('client_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_work_items', to='tenancy.tenant')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items_reviewing', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['due_on', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worked_on', models.DateField(db_index=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_billable', models.BooleanField(default=True)),
                ('narrative', models.CharField(blank=True, help_text="What was done. Appears on the client's invoice.", max_length=300)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_time_entries', to='tenancy.tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='practice.workitem')),
            ],
            options={
                'ordering': ['-worked_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-valid_from'],
                'indexes': [models.Index(fields=['user', '-valid_from'], name='ratecard_user_from_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='ratecard_window_sane')],
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'state', 'due_on'], name='work_tenant_state_due_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assigned_to', 'state'], name='work_assignee_state_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['client_tenant', 'state'], name='work_client_state_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['tenant', 'worked_on'], name='time_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'worked_on'], name='time_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(condition=models.Q(('invoiced_at__isnull', True), ('is_billable', True)), fields=['client_tenant', 'worked_on'], name='time_unbilled_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('is_billable', False), ('rate__gt', 0), _connector='OR'), name='timeentry_billable_has_rate'),
        ),
    ]
