# Generated by Django 5.2.17 on 2026-08-12 07:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('tenant_type', models.CharField(help_text='ORGANISATION, PRACTICE or DEALER — mirrors tenancy.Tenant.Type.', max_length=16)),
                ('interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=8)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('included_entities', models.PositiveSmallIntegerField(default=1)),
                ('included_users', models.PositiveSmallIntegerField(default=2)),
                ('extra_entity_minor', models.PositiveIntegerField(default=0)),
                ('extra_user_minor', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['tenant_type', 'sort_order', 'amount_minor'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, help_text='Assigned on issue, never reused. Blank while a draft.', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void'), ('CREDITED', 'Credited')], db_index=True, default='DRAFT', max_length=16)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('subtotal_minor', models.PositiveIntegerField(default=0)),
                ('tax_minor', models.PositiveIntegerField(default=0)),
                ('total_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('tax_rate_bps', models.PositiveSmallIntegerField(default=1800)),
                ('place_of_supply', models.CharField(blank=True, max_length=12)),
                ('customer_gstin', models.CharField(blank=True, max_length=20)),
                ('void_reason', models.CharField(blank=True, max_length=250)),
                ('credited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=9)),
                ('unit_amount_minor', models.PositiveIntegerField(default=0)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('sac_code', models.CharField(blank=True, max_length=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TRIALING', 'In trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Payment overdue'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], db_index=True, default='TRIALING', max_length=12)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField(db_index=True)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('entity_count', models.PositiveSmallIntegerField(default=1)),
                ('user_count', models.PositiveSmallIntegerField(default=1)),
                ('discount_bps', models.PositiveSmallIntegerField(default=0, help_text='Basis points. 1250 is 12.5%.')),
                ('provider', models.CharField(blank=True, help_text='stripe, payu, or empty for offline collection.', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('sold_by_dealer', models.ForeignKey(blank=True, limit_choices_to={'type': 'DEALER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_subscriptions', to='tenancy.tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('method', models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('NETBANKING', 'Net banking'), ('MANDATE', 'Standing mandate'), ('OFFLINE', 'Bank transfer or cheque'), ('CREDIT', 'Credit note applied')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('failure_reason', models.CharField(blank=True, max_length=250)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='payment_invoice_status_idx'), models.Index(fields=['tenant', '-received_on'], name='payment_tenant_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider', 'provider_reference'), name='payment_provider_reference_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='sub_status_period_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['sold_by_dealer'], name='sub_dealer_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('tenant',), name='subscription_one_live_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_end__gt', models.F('current_period_start'))), name='subscription_period_sane'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='invoice_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('status__in', ['ISSUED', 'PARTIALLY_PAID', 'OVERDUE'])), fields=['due_on'], name='invoice_unpaid_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='invoice_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('number__gt', ''), _connector='OR'), name='invoice_issued_has_number'),
        ),
    ]
