# Generated by Django 5.2.17 on 2026-08-12 06:12

import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obligations', '0002_rls'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('title', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=8)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_ANSWERED', 'Partially answered'), ('ANSWERED', 'Answered'), ('CLARIFICATION_NEEDED', 'Clarification needed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('assigned_email', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='tenancy.entity')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_requests', to='obligations.obligationinstance')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_raised', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['due_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('REMINDED', 'Reminder sent'), ('RESPONDED', 'Client responded'), ('REJECTED', 'Response rejected'), ('STATE_CHANGED', 'State changed'), ('NOTE', 'Note')], max_length=16)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_events', to='tenancy.entity')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rfi.informationrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=250)),
                ('help_text', models.CharField(blank=True, max_length=250)),
                ('kind', models.CharField(choices=[('DOCUMENT', 'A document'), ('DATA', 'A number or a date'), ('CONFIRMATION', 'A yes or no')], default='DOCUMENT', max_length=12)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('ordinal', models.PositiveSmallIntegerField(default=0)),
                ('response_value', models.CharField(blank=True, max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=250)),
                ('document_count', models.PositiveSmallIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='tenancy.entity')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfi.informationrequest')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['request', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='informationrequest',
            index=models.Index(fields=['tenant', 'state', 'due_on'], name='rfi_tenant_state_due_idx'),
        ),
        migrations.AddIndex(
            model_name='informationrequest',
            index=models.Index(fields=['assigned_to', 'state'], name='rfi_assignee_state_idx'),
        ),
        migrations.AddIndex(
            model_name='informationrequest',
            index=models.Index(fields=['obligation'], name='rfi_obligation_idx'),
        ),
        migrations.AddConstraint(
            model_name='informationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'DRAFT'), ('state', 'CANCELLED'), ('sent_at__isnull', False), _connector='OR'), name='request_sent_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['request', '-occurred_at'], name='rfievent_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitem',
            index=models.Index(fields=['request', 'ordinal'], name='rfiitem_request_ord_idx'),
        ),
    ]
