# Generated by Django 5.2.17 on 2026-09-10 03:24

import django.db.models.deletion
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderToken',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=8)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responder_tokens_issued', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_tokens', to='rfi.informationrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['request', 'status'], name='rfitoken_request_idx'), models.Index(fields=['expires_at'], name='rfitoken_expiry_idx')],
            },
        ),
    ]
