# Generated by Django 5.2.17 on 2026-08-11 19:31

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=200)),
                ('tenant_id_value', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='RUNNING', max_length=12)),
                ('result_ref', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['task_name', '-started_at'], name='taskrun_name_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, help_text='Denormalised actor description, so the row stays readable after the user is deleted.', max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ARCHIVE', 'Archived'), ('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('EXPORT', 'Exported'), ('TRANSITION', 'State changed'), ('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Sign-in failed'), ('LOGOUT', 'Signed out'), ('OTP_SENT', 'Verification code sent'), ('OTP_VERIFIED', 'Verification completed'), ('OTP_FAILED', 'Verification failed'), ('STEP_UP', 'Re-authenticated'), ('PERMISSION_CHANGE', 'Permissions changed'), ('ENGAGEMENT_GRANT', 'Access granted'), ('ENGAGEMENT_REVOKE', 'Access revoked'), ('PLATFORM_ACCESS', 'Platform-wide access'), ('IMPERSONATE', 'Support impersonation')], db_index=True, max_length=32)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('scope_reason', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acting_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries_impersonated', to=settings.AUTH_USER_MODEL)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='tenancy.entity')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit entries',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', '-occurred_at'], name='audit_tenant_time_idx'), models.Index(fields=['object_type', 'object_id', '-occurred_at'], name='audit_object_time_idx'), models.Index(fields=['actor', '-occurred_at'], name='audit_actor_time_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['occurred_at'], name='audit_occurred_brin_idx', pages_per_range=64)],
            },
        ),
    ]
