# Generated by Django 5.2.17 on 2026-08-11 18:38

import django.db.models.deletion
import django.utils.timezone
import stacos.accounts.models
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='phone number')),
                ('phone_verified', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text="STACOS platform staff. Unrelated to a customer's own hierarchy.")),
                ('security_stamp', models.UUIDField(default=stacos.core.ids.uuid7, editable=False)),
                ('locale', models.CharField(default='en-in', max_length=12)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', stacos.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN_NEW_DEVICE', 'Sign-in from a new device'), ('STEP_UP', 'Re-authentication for a sensitive action'), ('CHANNEL_CHANGE', 'Changing email or phone')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone_e164', models.CharField(max_length=20)),
                ('email_code_hash', models.CharField(max_length=64)),
                ('phone_code_hash', models.CharField(max_length=64)),
                ('email_satisfied', models.BooleanField(default=False)),
                ('phone_satisfied', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('next_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsSpendLedger',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('cost_units', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('failures', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'provider'), name='sms_spend_day_provider_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_first_seen', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_last_seen', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('login_method', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=64)),
                ('trusted_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.trusteddevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_e164'], name='user_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-last_seen_at'], name='user_last_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_verified', True), models.Q(('phone_e164', ''), _negated=True)), fields=('phone_e164',), name='user_verified_phone_unique'),
        ),
        migrations.AddIndex(
            model_name='pendingverification',
            index=models.Index(fields=['email', '-created_at'], name='pv_email_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingverification',
            index=models.Index(fields=['phone_e164', '-created_at'], name='pv_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingverification',
            index=models.Index(fields=['status', 'expires_at'], name='pv_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', '-last_used_at'], name='td_user_used_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_seen_at'], name='us_user_seen_idx'),
        ),
    ]
