# Generated by Django 5.2.17 on 2026-08-12 01:10

import stacos.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSpendLedger',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='WHATSAPP', max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('cost_units', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('unreachable', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'message spend entry',
                'verbose_name_plural': 'message spend entries',
            },
        ),
        migrations.DeleteModel(
            name='SmsSpendLedger',
        ),
        migrations.AddConstraint(
            model_name='messagespendledger',
            constraint=models.UniqueConstraint(fields=('day', 'channel', 'provider'), name='message_spend_day_channel_provider_uniq'),
        ),
    ]
