# Generated by Django 5.2.17 on 2026-08-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_whatsapp_message_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingverification',
            name='phone_unreachable',
            field=models.BooleanField(default=False),
        ),
    ]
