# Generated by Django 5.2.17 on 2026-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pending_verification_phone_unreachable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingverification',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_e164',
            field=models.CharField(blank=True, max_length=20, verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='WhatsApp number'),
        ),
    ]
