# Generated by Django 5.2.17 on 2026-08-12 02:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import stacos.catalog.models
import stacos.core.ids
import stacos.engine.types
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurisdictions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Permanent handle, e.g. IN-GST-GSTR3B-MONTHLY. Never renamed once shipped.', max_length=64, unique=True)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('family', models.CharField(blank=True, db_index=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='jurisdictions.authority')),
            ],
            options={
                'ordering': ['country', 'family', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DefinitionVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('plain_language_summary', models.TextField(blank=True)),
                ('statutory_reference', models.CharField(blank=True, help_text="Section and rule, e.g. 'Section 39 CGST Act r/w Rule 61'.", max_length=250)),
                ('filing_portal_url', models.URLField(blank=True)),
                ('periodicity', models.CharField(choices=[(stacos.engine.types.Periodicity['MONTHLY'], stacos.engine.types.Periodicity['MONTHLY']), (stacos.engine.types.Periodicity['QUARTERLY'], stacos.engine.types.Periodicity['QUARTERLY']), (stacos.engine.types.Periodicity['HALF_YEARLY'], stacos.engine.types.Periodicity['HALF_YEARLY']), (stacos.engine.types.Periodicity['ANNUAL'], stacos.engine.types.Periodicity['ANNUAL']), (stacos.engine.types.Periodicity['EVENT_BASED'], stacos.engine.types.Periodicity['EVENT_BASED']), (stacos.engine.types.Periodicity['ONE_TIME'], stacos.engine.types.Periodicity['ONE_TIME'])], max_length=16)),
                ('period_anchor', models.CharField(default='FY', max_length=10)),
                ('jurisdictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default=list, size=None)),
                ('applicability_rule', models.JSONField(blank=True, default=dict, help_text='Declarative rule evaluated by stacos.engine.rules. Empty applies to everyone.')),
                ('facts_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('instance_scope', models.CharField(choices=[(stacos.engine.types.InstanceScope['ENTITY'], stacos.engine.types.InstanceScope['ENTITY']), (stacos.engine.types.InstanceScope['REGISTRATION'], stacos.engine.types.InstanceScope['REGISTRATION']), (stacos.engine.types.InstanceScope['PREMISES'], stacos.engine.types.InstanceScope['PREMISES'])], default=stacos.engine.types.InstanceScope['ENTITY'], help_text='ENTITY, REGISTRATION or PREMISES. GSTR-3B is per GSTIN, not per company.', max_length=16)),
                ('scope_selector', models.JSONField(blank=True, default=dict)),
                ('due_rule', models.JSONField(default=dict)),
                ('evidence_requirements', models.JSONField(blank=True, default=list)),
                ('default_owner_role', models.CharField(blank=True, max_length=60)),
                ('penalty_summary', models.CharField(blank=True, max_length=250)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('HIGH', 'Verified against the statute'), ('MEDIUM', 'Believed correct, not formally verified'), ('LOW', 'Provisional — shown with a caveat')], default='MEDIUM', max_length=8)),
                ('source_path', models.CharField(blank=True, max_length=250)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.compliancedefinition')),
            ],
            options={
                'ordering': ['definition', '-version'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentExtension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('definition_code', models.SlugField(max_length=64)),
                ('kind', models.CharField(choices=[('EXTENSION', 'Due date moved later'), ('ADVANCEMENT', 'Due date moved earlier'), ('WAIVER', 'Late fee or interest waived — date unchanged'), ('AMNESTY', 'Window to file old periods without penalty')], max_length=12)),
                ('notification_reference', models.CharField(help_text="e.g. 'Notification 07/2026 – Central Tax dated 31.03.2026'.", max_length=120)),
                ('notification_url', models.URLField(blank=True)),
                ('period_key', models.CharField(blank=True, db_index=True, max_length=32)),
                ('new_due_date', models.DateField(blank=True, help_text='Required for EXTENSION and ADVANCEMENT; meaningless for WAIVER.', null=True)),
                ('jurisdictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default=list, size=None)),
                ('scope_rule', models.JSONField(blank=True, default=dict)),
                ('relief', models.JSONField(blank=True, default=dict)),
                ('amnesty_window_start', models.DateField(blank=True, null=True)),
                ('amnesty_window_end', models.DateField(blank=True, null=True)),
                ('published_at', models.DateField(help_text='Date of the notification, not of data entry.')),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', 'definition_code'],
                'indexes': [models.Index(fields=['definition_code', 'period_key'], name='extension_code_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['EXTENSION', 'ADVANCEMENT']), _negated=True), ('new_due_date__isnull', False), _connector='OR'), name='extension_has_new_date')],
            },
        ),
        migrations.AddIndex(
            model_name='compliancedefinition',
            index=models.Index(fields=['country', 'category'], name='definition_country_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancedefinition',
            index=models.Index(fields=['country', 'is_active'], name='definition_country_active_idx'),
        ),
        migrations.AddIndex(
            model_name='definitionversion',
            index=models.Index(fields=['status', 'effective_from'], name='defversion_status_eff_idx'),
        ),
        migrations.AddIndex(
            model_name='definitionversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['facts_used'], name='defversion_facts_gin'),
        ),
        migrations.AddConstraint(
            model_name='definitionversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='defversion_code_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='definitionversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='defversion_window_sane'),
        ),
        migrations.AddConstraint(
            model_name='definitionversion',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'PUBLISHED')), expressions=[('definition', '='), (stacos.catalog.models.DateRange('effective_from', 'effective_to', models.Value('[)')), '&&')], name='defversion_no_overlapping_published'),
        ),
    ]
