# Generated by Django 5.2.17 on 2026-09-03 16:19

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('jurisdictions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedefinition',
            name='sector_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=40), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='compliancedefinition',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=40), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='compliancedefinition',
            name='trigger_kind',
            field=models.CharField(choices=[('STATUTORY_PERIODIC', 'Recurring statutory filing'), ('EVENT_DRIVEN', 'Triggered by something happening'), ('RENEWAL', 'Licence or registration renewal'), ('GOVERNANCE', 'Meeting, register or resolution'), ('INTERNAL', 'Internal control, no external filing')], db_index=True, default='STATUTORY_PERIODIC', max_length=20),
        ),
        migrations.AddField(
            model_name='definitionversion',
            name='possible_entity_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='definitionversion',
            name='probe_signature',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='definitionversion',
            name='trigger_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='compliancedefinition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='definition_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='compliancedefinition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sector_tags'], name='definition_sector_gin'),
        ),
        migrations.AddIndex(
            model_name='definitionversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['possible_entity_types'], name='defversion_possible_gin'),
        ),
    ]
