# Generated by Django 5.2.17 on 2026-09-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definitionversion',
            name='workflow_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
