# Generated by Django 5.2.17 on 2026-09-03 16:45

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import stacos.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_compliancedefinition_sector_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('definition_codes', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=64), default=list, size=None)),
                ('suggestion_rule', models.JSONField(blank=True, default=dict)),
                ('facts_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=40), blank=True, default=list, size=None)),
                ('jurisdictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('source_path', models.CharField(blank=True, max_length=250)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['country', 'name'],
                'indexes': [models.Index(fields=['country', 'is_active'], name='pack_country_active_idx'), django.contrib.postgres.indexes.GinIndex(fields=['definition_codes'], name='pack_definitions_gin'), django.contrib.postgres.indexes.GinIndex(fields=['facts_used'], name='pack_facts_gin')],
            },
        ),
    ]
