# Generated by Django 5.2.17 on 2026-09-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_definitionversion_workflow_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='definitionversion',
            name='penalty_rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
