# Generated by Django 5.2.17 on 2026-08-12 06:12

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
import stacos.vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('EVIDENCE', 'Evidence for a filing'), ('RETURN', 'Filed return or acknowledgement'), ('CHALLAN', 'Tax payment challan'), ('CERTIFICATE', 'Certificate or licence'), ('NOTICE', 'Notice from an authority'), ('CORRESPONDENCE', 'Letter or email'), ('FINANCIAL', 'Financial statement or ledger'), ('AGREEMENT', 'Contract or agreement'), ('IDENTITY', 'Identity or registration document'), ('MINUTES', 'Meeting minutes or resolution'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('classification', models.CharField(choices=[('GENERAL', 'General'), ('FINANCIAL', 'Financial'), ('PERSONAL', 'Contains personal data'), ('PRIVILEGED', 'Legally privileged')], default='GENERAL', max_length=12)),
                ('source', models.CharField(choices=[('UPLOAD', 'Uploaded by a user'), ('EMAIL', 'Received by email'), ('PORTAL', 'Fetched from a government portal'), ('GENERATED', 'Generated by STACOS')], default='UPLOAD', max_length=12)),
                ('file', models.FileField(max_length=500, upload_to=stacos.vault.models.upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=250)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('note', models.TextField(blank=True)),
                ('period_key', models.CharField(blank=True, db_index=True, max_length=32)),
                ('retain_until', models.DateField(blank=True, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scan_result', models.CharField(blank=True, max_length=40)),
                ('extracted_text', models.TextField(blank=True)),
                ('entity', models.ForeignKey(blank=True, help_text='Null for tenant-level documents such as an engagement letter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='vault.document')),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_downloads', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('OBLIGATION', 'Obligation'), ('REQUEST_ITEM', 'Information request item'), ('NOTICE', 'Notice'), ('RETURN', 'Return preparation'), ('MEETING', 'Meeting'), ('ENTITY', 'Entity'), ('INVOICE', 'Invoice')], db_index=True, max_length=20)),
                ('target_id', models.UUIDField(db_index=True)),
                ('evidence_key', models.CharField(blank=True, max_length=60)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='vault.document')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='tenancy.entity')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=500, upload_to='vault/versions/')),
                ('content_hash', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('replaced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vault.document')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['document', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', '-created_at'], name='document_tenant_time_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity', 'kind'], name='document_entity_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='document_tags_gin'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('tenant', 'content_hash'), name='document_tenant_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['document', '-downloaded_at'], name='docdownload_doc_time_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['target_type', 'target_id'], name='doclink_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.UniqueConstraint(fields=('document', 'target_type', 'target_id', 'evidence_key'), name='doclink_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='docversion_document_version_uniq'),
        ),
    ]
