# Generated by Django 5.2.17 on 2026-08-12 06:56

import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obligations', '0002_rls'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPreparation',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('form_type', models.CharField(db_index=True, help_text='GSTR-3B, GSTR-1, 24Q, ITR-6 — denormalised from the definition.', max_length=40)),
                ('period_key', models.CharField(db_index=True, max_length=32)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARED', 'Prepared'), ('REWORK', 'Sent back for rework'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved for filing'), ('FILED', 'Filed')], db_index=True, default='DRAFT', max_length=12)),
                ('figures', models.JSONField(blank=True, default=dict)),
                ('tax_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('filing_reference', models.CharField(blank=True, max_length=120)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_approved', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_preparations', to='tenancy.entity')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_filed', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='obligations.obligationinstance')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('GSTR2B_VS_BOOKS', 'GSTR-2B against purchase register'), ('GSTR1_VS_BOOKS', 'GSTR-1 against sales register'), ('GSTR3B_VS_GSTR1', 'GSTR-3B against GSTR-1'), ('FORM26AS_VS_BOOKS', 'Form 26AS against books'), ('BOOKS_VS_BANK', 'Books against bank'), ('OTHER', 'Other')], max_length=24)),
                ('left_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('right_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='tenancy.entity')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='returns.returnpreparation')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDifference',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=120)),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('left_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('right_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('resolution', models.CharField(choices=[('UNRESOLVED', 'Not yet explained'), ('TIMING', 'Timing difference — will reverse'), ('SUPPLIER_ERROR', 'Supplier has not filed'), ('BOOKS_ERROR', 'Our books are wrong'), ('ACCEPTED', 'Accepted as a permanent difference'), ('CARRIED_FORWARD', 'Carried forward to the next period')], default='UNRESOLVED', max_length=16)),
                ('resolution_note', models.CharField(blank=True, max_length=250)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_differences', to='tenancy.entity')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='returns.reconciliation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['reference'],
                'indexes': [models.Index(fields=['reconciliation', 'resolution'], name='recondiff_resolution_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='returnpreparation',
            index=models.Index(fields=['tenant', 'state'], name='prep_tenant_state_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpreparation',
            index=models.Index(fields=['entity', 'form_type', 'period_key'], name='prep_form_period_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpreparation',
            index=models.Index(fields=['prepared_by', 'state'], name='prep_maker_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnpreparation',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), ('prepared_by__isnull', True), models.Q(('reviewed_by', models.F('prepared_by')), _negated=True), _connector='OR'), name='preparation_reviewer_is_not_preparer'),
        ),
        migrations.AddConstraint(
            model_name='returnpreparation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'FILED'), _negated=True), ('filed_on__isnull', False), _connector='OR'), name='preparation_filed_has_date'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['preparation', '-run_at'], name='recon_prep_time_idx'),
        ),
    ]
