# Generated by Django 5.2.17 on 2026-09-10 05:58

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
import stacos.engine.lifecycle
import stacos.engine.types
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationInstance',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('definition_code', models.SlugField(max_length=64)),
                ('definition_version', models.PositiveIntegerField(default=1)),
                ('scope_kind', models.CharField(choices=[(stacos.engine.types.InstanceScope['ENTITY'], stacos.engine.types.InstanceScope['ENTITY']), (stacos.engine.types.InstanceScope['REGISTRATION'], stacos.engine.types.InstanceScope['REGISTRATION']), (stacos.engine.types.InstanceScope['PREMISES'], stacos.engine.types.InstanceScope['PREMISES'])], default=stacos.engine.types.InstanceScope['ENTITY'], max_length=16)),
                ('scope_ref', models.CharField(blank=True, max_length=100)),
                ('scope_label', models.CharField(blank=True, max_length=150)),
                ('scope_jurisdiction', models.CharField(blank=True, db_index=True, max_length=12)),
                ('period_key', models.CharField(db_index=True, max_length=32)),
                ('period_label', models.CharField(blank=True, max_length=120)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('occurrence', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('original_due_date', models.DateField(blank=True, null=True)),
                ('applied_extension_reference', models.CharField(blank=True, max_length=120)),
                ('relief', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[(stacos.engine.lifecycle.State['NOT_STARTED'], 'Not started'), (stacos.engine.lifecycle.State['INFO_REQUESTED'], 'Information requested'), (stacos.engine.lifecycle.State['IN_PREPARATION'], 'In preparation'), (stacos.engine.lifecycle.State['PENDING_REVIEW'], 'Pending review'), (stacos.engine.lifecycle.State['PENDING_CLIENT_APPROVAL'], 'Pending client approval'), (stacos.engine.lifecycle.State['READY_TO_FILE'], 'Ready to file'), (stacos.engine.lifecycle.State['FILED'], 'Filed'), (stacos.engine.lifecycle.State['CLOSED'], 'Closed'), (stacos.engine.lifecycle.State['NOT_APPLICABLE'], 'Not applicable'), (stacos.engine.lifecycle.State['DEFERRED'], 'Deferred'), (stacos.engine.lifecycle.State['DISPUTED'], 'Disputed')], default=stacos.engine.lifecycle.State['NOT_STARTED'], max_length=28)),
                ('state_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('filing_reference', models.CharField(blank=True, help_text='Acknowledgement or challan number.', max_length=120)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_role', models.CharField(blank=True, max_length=60)),
                ('confirmed', models.BooleanField(default=True)),
                ('missing_facts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('needs_input', models.CharField(blank=True, max_length=64)),
                ('retroactive', models.BooleanField(default=False)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('supersede_reason', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_obligations', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ObligationEvent',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('TRANSITION', 'State changed'), ('MATERIALISED', 'Added to the calendar'), ('DATE_CHANGED', 'Due date changed'), ('EXTENSION_APPLIED', 'Government extension applied'), ('SUPERSEDED', 'No longer applicable'), ('ASSIGNED', 'Assigned'), ('NOTE', 'Note added'), ('EVIDENCE_ADDED', 'Evidence attached')], max_length=20)),
                ('from_state', models.CharField(blank=True, max_length=28)),
                ('to_state', models.CharField(blank=True, max_length=28)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_events', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='obligations.obligationinstance')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ObligationSuppression',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition_code', models.SlugField(max_length=64)),
                ('scope_ref', models.CharField(blank=True, max_length=100)),
                ('period_key', models.CharField(blank=True, max_length=32)),
                ('occurrence', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('NOT_APPLICABLE', 'Does not apply to us'), ('DEFERRED', 'Postponed')], default='NOT_APPLICABLE', max_length=20)),
                ('reason', models.TextField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_suppressions', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EntityEvent',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('occurred_on', models.DateField()),
                ('scope_ref', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('subject_ref', models.CharField(blank=True, max_length=100)),
                ('subject_label', models.CharField(blank=True, max_length=200)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('supersede_reason', models.CharField(blank=True, max_length=250)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='tenancy.entity')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['entity', 'key', '-occurred_on'],
                'indexes': [models.Index(fields=['entity', 'key', '-occurred_on'], name='entityevent_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True)), fields=('entity', 'key', 'scope_ref', 'occurred_on', 'subject_ref'), name='entityevent_identity_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MaterialisationRun',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('NIGHTLY', 'Nightly horizon roll'), ('PROFILE_CHANGE', 'Profile changed'), ('CATALOG_PUBLISH', 'Catalog published'), ('MANUAL', 'Requested by a user'), ('ONBOARDING', 'Entity onboarded'), ('EVENT_RECORDED', 'Entity event recorded')], max_length=20)),
                ('catalog_fingerprint', models.CharField(blank=True, max_length=32)),
                ('horizon_start', models.DateField()),
                ('horizon_end', models.DateField()),
                ('as_of', models.DateField()),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('superseded_count', models.PositiveIntegerField(default=0)),
                ('archived_count', models.PositiveIntegerField(default=0)),
                ('revived_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('diagnostics', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialisation_runs', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', '-created_at'], name='matrun_entity_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObligationInclusion',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition_code', models.SlugField(max_length=64)),
                ('source', models.CharField(choices=[('USER', 'Chosen one at a time'), ('PACK', 'Came with a compliance pack')], default='USER', max_length=8)),
                ('pack_code', models.SlugField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_inclusions', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'definition_code'], name='inclusion_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('entity', 'definition_code'), name='inclusion_identity_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='obligationinstance',
            index=models.Index(condition=models.Q(('state__in', ['DEFERRED', 'DISPUTED', 'INFO_REQUESTED', 'IN_PREPARATION', 'NOT_STARTED', 'PENDING_CLIENT_APPROVAL', 'PENDING_REVIEW', 'READY_TO_FILE']), ('archived_at__isnull', True)), fields=['tenant', 'due_date'], name='obligation_open_due_idx'),
        ),
        migrations.AddIndex(
            model_name='obligationinstance',
            index=models.Index(fields=['entity', 'due_date'], name='obligation_entity_due_idx'),
        ),
        migrations.AddIndex(
            model_name='obligationinstance',
            index=models.Index(fields=['definition_code', 'period_key'], name='obligation_code_period_idx'),
        ),
        migrations.AddIndex(
            model_name='obligationinstance',
            index=models.Index(fields=['assigned_to', 'due_date'], name='obligation_assignee_due_idx'),
        ),
        migrations.AddIndex(
            model_name='obligationinstance',
            index=models.Index(fields=['tenant', 'category'], name='obligation_tenant_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='obligationinstance',
            constraint=models.UniqueConstraint(fields=('entity', 'definition_code', 'scope_ref', 'period_key', 'occurrence'), name='obligation_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='obligationinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['FILED', 'CLOSED']), _negated=True), ('filed_on__isnull', False), _connector='OR'), name='obligation_filed_has_date'),
        ),
        migrations.AddIndex(
            model_name='obligationevent',
            index=models.Index(fields=['obligation', '-occurred_at'], name='oblevent_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='obligationsuppression',
            index=models.Index(fields=['entity', 'definition_code'], name='suppression_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='obligationsuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('entity', 'definition_code', 'scope_ref', 'period_key', 'occurrence'), name='suppression_identity_uniq'),
        ),
    ]
