# Generated by Django 5.2.17 on 2026-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationinstance',
            name='confirmed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
