# Generated by Django 5.2.17 on 2026-09-03 16:19

import django.db.models.deletion
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0002_rls'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationInclusion',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition_code', models.SlugField(max_length=64)),
                ('source', models.CharField(choices=[('USER', 'Chosen one at a time'), ('PACK', 'Came with a compliance pack')], default='USER', max_length=8)),
                ('pack_code', models.SlugField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='entityevent',
            name='entityevent_identity_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='obligationsuppression',
            name='suppression_identity_uniq',
        ),
        migrations.AddField(
            model_name='entityevent',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entityevent',
            name='subject_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='entityevent',
            name='subject_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entityevent',
            name='supersede_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='entityevent',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obligationsuppression',
            name='occurrence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialisationrun',
            name='trigger',
            field=models.CharField(choices=[('NIGHTLY', 'Nightly horizon roll'), ('PROFILE_CHANGE', 'Profile changed'), ('CATALOG_PUBLISH', 'Catalog published'), ('MANUAL', 'Requested by a user'), ('ONBOARDING', 'Entity onboarded'), ('EVENT_RECORDED', 'Entity event recorded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obligationinstance',
            name='period_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='entityevent',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True)), fields=('entity', 'key', 'scope_ref', 'occurred_on', 'subject_ref'), name='entityevent_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='obligationsuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('entity', 'definition_code', 'scope_ref', 'period_key', 'occurrence'), name='suppression_identity_uniq'),
        ),
        migrations.AddField(
            model_name='obligationinclusion',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obligationinclusion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_inclusions', to='tenancy.entity'),
        ),
        migrations.AddField(
            model_name='obligationinclusion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='obligationinclusion',
            index=models.Index(fields=['entity', 'definition_code'], name='inclusion_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='obligationinclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('entity', 'definition_code'), name='inclusion_identity_uniq'),
        ),
    ]
