# Generated by Django 5.2.17 on 2026-09-14 06:24

import django.db.models.deletion
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0003_obligationinstance_confirmed_by_user'),
        ('tenancy', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationevent',
            name='kind',
            field=models.CharField(choices=[('TRANSITION', 'State changed'), ('MATERIALISED', 'Added to the calendar'), ('DATE_CHANGED', 'Due date changed'), ('EXTENSION_APPLIED', 'Government extension applied'), ('SUPERSEDED', 'No longer applicable'), ('ASSIGNED', 'Assigned'), ('NOTE', 'Note added'), ('EVIDENCE_ADDED', 'Evidence attached'), ('STEP_ASSIGNED', 'Checklist step assigned'), ('STEP_COMPLETED', 'Checklist step completed'), ('STEP_REOPENED', 'Checklist step reopened'), ('STEP_BLOCKED', 'Checklist step blocked'), ('STEP_UNBLOCKED', 'Checklist step unblocked')], max_length=20),
        ),
        migrations.CreateModel(
            name='ObligationStep',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('PREPARE', 'Prepare'), ('REVIEW', 'Review'), ('APPROVE', 'Approve'), ('FILE', 'File')], max_length=8)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='PENDING', max_length=8)),
                ('blocked_reason', models.CharField(blank=True, max_length=300)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_obligation_steps', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.entity')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='obligations.obligationinstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['obligation', 'order'],
                'indexes': [models.Index(fields=['assigned_to', 'state'], name='obligationstep_assignee_idx')],
                'constraints': [models.UniqueConstraint(fields=('obligation', 'key'), name='obligationstep_identity_uniq')],
            },
        ),
    ]
