# Generated by Django 5.2.17 on 2026-09-09 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0004_rls_inclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationinstance',
            name='missing_facts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
    ]
