# Generated by Django 5.2.17 on 2026-09-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0005_obligationstep_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationstep',
            name='days_before_due',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obligationstep',
            name='evidence_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='obligationstep',
            name='requires_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obligationstep',
            name='role',
            field=models.CharField(choices=[('PREPARE', 'Prepare'), ('REVIEW', 'Review'), ('APPROVE', 'Approve'), ('SIGN', 'Sign')], max_length=8),
        ),
    ]
