# Generated by Django 5.2.17 on 2026-09-15 03:46

from django.db import migrations, models

import stacos.obligations.models


class Migration(migrations.Migration):
    dependencies = [
        ("obligations", "0006_obligationstep_days_before_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligationinstance",
            name="acknowledgement",
            field=models.FileField(
                blank=True,
                max_length=300,
                upload_to=stacos.obligations.models.acknowledgement_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="obligationinstance",
            name="acknowledgement_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="obligationinstance",
            name="expected_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="obligationinstance",
            name="pending_reason",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="obligationinstance",
            name="pending_reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
