# Generated by Django 5.2.17 on 2026-09-16 04:36

import stacos.engine.lifecycle
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0009_calendarfeedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationinstance',
            name='state',
            field=models.CharField(choices=[(stacos.engine.lifecycle.State['NOT_STARTED'], 'Not started'), (stacos.engine.lifecycle.State['INFO_REQUESTED'], 'Information requested'), (stacos.engine.lifecycle.State['IN_PREPARATION'], 'In progress'), (stacos.engine.lifecycle.State['PENDING_REVIEW'], 'Pending review'), (stacos.engine.lifecycle.State['PENDING_CLIENT_APPROVAL'], 'Pending client approval'), (stacos.engine.lifecycle.State['READY_TO_FILE'], 'Ready to file'), (stacos.engine.lifecycle.State['FILED'], 'Filed'), (stacos.engine.lifecycle.State['CLOSED'], 'Closed'), (stacos.engine.lifecycle.State['NOT_APPLICABLE'], 'Not applicable'), (stacos.engine.lifecycle.State['DEFERRED'], 'Deferred'), (stacos.engine.lifecycle.State['DISPUTED'], 'Disputed')], default=stacos.engine.lifecycle.State['NOT_STARTED'], max_length=28),
        ),
    ]
