# Generated by Django 5.2.17 on 2026-09-28 12:46

import django.contrib.postgres.fields
import django.db.models.deletion
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models

from stacos.core.rls import disable_rls_statements, enable_rls_statements

#: Row-Level Security on both new tables, in the migration that creates them —
#: see ``0005_obligationstep_rls.py``. ``manage.py ensure_rls`` fails CI without it.
RLS_TABLES = ("obligations_customobligation", "obligations_customobligationversion")


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0011_relabel_submitted_and_completed'),
        ('tenancy', '0004_invitation_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialisationrun',
            name='trigger',
            field=models.CharField(choices=[('NIGHTLY', 'Nightly horizon roll'), ('PROFILE_CHANGE', 'Profile changed'), ('CATALOG_PUBLISH', 'Catalog published'), ('MANUAL', 'Requested by a user'), ('ONBOARDING', 'Entity onboarded'), ('EVENT_RECORDED', 'Entity event recorded'), ('CUSTOM_OBLIGATION', 'Own obligation changed')], max_length=20),
        ),
        migrations.CreateModel(
            name='CustomObligation',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(editable=False, max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_reference', models.CharField(blank=True, max_length=250)),
                ('consequence', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('evidence_labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('evidence_mandatory', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdraw_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_obligations', to='tenancy.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CustomObligationVersion',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('periodicity', models.CharField(max_length=16)),
                ('period_anchor', models.CharField(choices=[('FY', 'Financial year'), ('CALENDAR', 'Calendar year')], default='FY', max_length=10)),
                ('due_mode', models.CharField(choices=[('DAYS_AFTER_PERIOD', 'A number of days after the period ends'), ('DAY_OF_NEXT_MONTH', 'On a day of the month after the period ends')], max_length=20)),
                ('due_days', models.PositiveSmallIntegerField(default=0)),
                ('due_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shift_to_working_day', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.entity')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='obligations.customobligation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['obligation', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='customobligation',
            index=models.Index(fields=['entity', 'withdrawn_at'], name='customobl_entity_live_idx'),
        ),
        migrations.AddConstraint(
            model_name='customobligationversion',
            constraint=models.UniqueConstraint(fields=('obligation', 'version'), name='customoblversion_identity_uniq'),
        ),
    ] + [
        migrations.RunSQL(
            sql="\n".join(enable_rls_statements(table)),
            reverse_sql="\n".join(disable_rls_statements(table)),
        )
        for table in RLS_TABLES
    ]
