# Generated by Django 5.2.17 on 2026-09-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0012_custom_obligations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customobligation',
            name='evidence_labels',
        ),
        migrations.RemoveField(
            model_name='customobligation',
            name='evidence_mandatory',
        ),
        migrations.RemoveField(
            model_name='customobligation',
            name='source_reference',
        ),
        migrations.RemoveField(
            model_name='customobligationversion',
            name='due_day_of_month',
        ),
        migrations.RemoveField(
            model_name='customobligationversion',
            name='due_days',
        ),
        migrations.RemoveField(
            model_name='customobligationversion',
            name='due_mode',
        ),
        migrations.RemoveField(
            model_name='customobligationversion',
            name='shift_to_working_day',
        ),
    ]
