# Generated by Django 5.2.17 on 2026-09-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0013_drop_custom_obligation_due_evidence_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobligationversion',
            name='due_day_of_month',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customobligationversion',
            name='due_offset_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
