# Generated by Django 5.2.17 on 2026-09-10 05:58

import django.db.models.deletion
import django.utils.timezone
import stacos.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('basis', models.CharField(choices=[('RECURRING', 'Share of every invoice'), ('FIRST_INVOICE', 'First invoice only'), ('LIMITED_TERM', 'Limited term')], default='RECURRING', max_length=16)),
                ('rate_bps', models.PositiveSmallIntegerField(help_text='Basis points of net invoice value. 1500 is 15%.')),
                ('term_months', models.PositiveSmallIntegerField(default=12)),
                ('parent_share_bps', models.PositiveSmallIntegerField(default=0)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['tenant', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_minor', models.BigIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_approved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.UUIDField(default=stacos.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.UUIDField(db_index=True)),
                ('invoice_number', models.CharField(blank=True, max_length=40)),
                ('amount_minor', models.BigIntegerField()),
                ('base_amount_minor', models.PositiveIntegerField(default=0)),
                ('rate_bps', models.PositiveSmallIntegerField(default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued'), ('APPROVED', 'Approved for payout'), ('PAID', 'Paid'), ('CLAWED_BACK', 'Clawed back')], db_index=True, default='ACCRUED', max_length=12)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('client_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='tenancy.tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='dealers.commissionplan')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='dealers.payout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='commissionplan_window_sane'),
        ),
        migrations.AddConstraint(
            model_name='commissionplan',
            constraint=models.CheckConstraint(condition=models.Q(('rate_bps__lte', 10000)), name='commissionplan_rate_sane'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['tenant', 'status'], name='payout_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payout_period_sane'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), ('payment_reference__gt', ''), _connector='OR'), name='payout_paid_has_reference'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['tenant', 'status'], name='commission_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['client_tenant'], name='commission_client_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACCRUED', 'APPROVED', 'PAID'])), fields=('tenant', 'invoice_id'), name='commission_one_accrual_per_invoice'),
        ),
    ]
